### ISSUE TITLE
gs backend misbehaves with backpressure

### ISSUE THREAD

**Issue by seamusabshere** [dbcrossbar/dbcrossbar#103]
if you are copying from gs to a slow destination (such as bigml), then gsutil's network connection can time out, which is not recoverable

**Comment by emk** [comment]
This is normally only triggered using `--stream-size` and slow destinations like BigML, because `--stream-size` causes a mismatch between input stream boundaries and output stream boundaries. This mismatch can lead to long pauses partway through an input stream.

Fixing this depends on fixing #112.
