### ISSUE TITLE
bigquery errors only appear in BigQuery console

### ISSUE THREAD

**Issue by seamusabshere** [dbcrossbar/dbcrossbar#110]
Heavy production use of dbcrossbar has shown that there are 2 failure modes when copying to/from bigquery:

1. Query fails (from `bq query`)
2. Job fails (from `bq load`)

In both cases, all dbcrossbar tells you is (this error is so common that our customer success team memorized it)

```
Error: `bq query` failed with exit code: 1
```

You CANNOT turn up `RUST_LOG` to see the error. The only way to see what's wrong is to log into the BigQuery console and check out the Query History or Job History. Apart from taking a long time to look up, the history is truncated after just a few dozen queries/requests, so you have to check almost immediately or the error is lost to history.

**Comment by emk** [comment]
I suspect this will be much easier to fix once we get rid of `bq` as per #112.

**Comment by emk** [comment]
Fixed by 19b93d12cb237cdd0bf6a8e9f0291e0485f44f89.
