### ISSUE TITLE
Add struct types to portable schema and BigQuery

### ISSUE THREAD

**Issue by emk** [dbcrossbar/dbcrossbar#129]
- [x] Add to portable schema.
- [x] Add to BigQuery.
- [x] Implement an experimental `dbcrossbar-ts` driver that allows TypeScript-like schemas.
- [ ] Review PostgreSQL `json[]` issue with @seamusabshere

**Comment by seamusabshere** [comment]
@emk what's the deal with `json[]`?

**Comment by emk** [comment]
@seamusabshere In a nutshell, if you write:

```sql
CREATE TABLE example (
  id int NOT NULL,
  metadata jsonb[]
)
```

...you'll actually get a `jsonb` column, not the `jsonb[]` column that you asked for. Similarly, if you copy a BigQuery `ARRAY<STRUCT<...>>` to PostgreSQL, you'll get a `jsonb` column, not a `jsonb[]`, which is more "natural".

This deviates from `dbcrossbar`'s increasingly strict philosophy of "copy everything as exactly as possible," which has become more strict after dealing with the BigQuery column name debacle. (In that case, trying to "fix" invalid BigQuery column names automatically led to a number of subtle, maddening bugs.)

I'm pretty sure that mapping `jsonb[]` to `jsonb` is going to end badly, especially because of issues like the first example, where we basically ignore the clear instructions in a `CREATE TABLE` statement.

I suspect that we'll eventually need to break compatibility here for one reason or another, and so I'd just as soon get it over with.
