### ISSUE TITLE
BigQuery cannot upsert on "*" because it is not REQUIRED

### ISSUE THREAD

**Issue by seamusabshere** [dbcrossbar/dbcrossbar#141]
```
$ dbcrossbar cp --if-exists=upsert-on:email csv:test.csv bigquery:myproject:mydataset.mytable
Error: BigQuery cannot upsert on "email" because it is not REQUIRED (aka NOT NULL)
```

what i got: error

what i expected: it would create a new table and insert into it

**Comment by emk** [comment]
If you upsert into a table that doesn't exist, you need to supply a schema using `--schema`. If you don't supply a schema (like in the example you gave), then it will infer the schema from the source `csv:test.csv`. Schemas inferred from CSV files will mark all columns as `TEXT` (and not `TEXT NOT NULL`).

Try this again with a schema please, and make sure that it contains `email TEXT NOT NULL` . Please let me know if this works!

**Comment by seamusabshere** [comment]
@emk 

i understand that would fix it - but constructing and passing a schema can be very laborious, if all you're doing is setting a single col to NOT NULL

i would advocate for creating the column as not null if you're upserting against it. otherwise this is a guaranteed fail

**Comment by emk** [comment]
Unfortunately, that would require a fair bit of abstraction violation and refactoring of the internals. The `csv:` input driver has no idea what the output driver plans to do with the data, so there's no way for it to magically look ahead and compute a different schema. And the output driver shouldn't just randomly change the schema you give it.

I recommend:

```sh
dbcrossbar schema conv csv:in.csv postgres-sql:schema.sql
# edit schema.sql
dbcrossbar cp --if-exists=upsert-on:email --schema=schema.sql \
  csv:test.csv \
  bigquery:myproject:mydataset.mytable
```

At some point I plan to add a `dbcrossbar schema infer` command that actually reads a few thousand rows and determines the best schema it can based on probability.

**Comment by seamusabshere** [comment]
ok that makes sense!

and yeah, for future readers, the example above should use `dbcrossbar-schema` so you can easily parse it and insert your `is_nullable: false`
