### ISSUE TITLE
Live replication or one-time snapshot?

### ISSUE THREAD

**Issue by sodabrew** [dbcrossbar/dbcrossbar#161]
I saw this service highlighted on a Postgres weekly email newsletter. Does it connect to Postgres and other databases as a replication client or is it more like a "sqldump" tool that runs just once?

**Comment by seamusabshere** [comment]
hi, it runs just once when you invoke it. It's not continuous.

**Comment by emk** [comment]
dbcrossbar's job is to copy a single table at time, as a one-shot action. It's not a general synchronization tool, unfortunately.
