### ISSUE TITLE
gs/bigquery: Error: accessDenied while writing data

### ISSUE THREAD

**Issue by blakew** [dbcrossbar/dbcrossbar#181]
Getting the following error in CI:

```Error: accessDenied at gs://....csv: Access Denied: BigQuery BigQuery: Permission denied while writing data.```

**Comment by emk** [comment]
This is a permission error. See https://www.dbcrossbar.org/gs.html#configuration--authentication for docs that might help.

**Comment by seamusabshere** [comment]
this is actually a transient error that may be possible to retry from

```
stderr: Error: accessDenied at gs://xxx/000000000000.csv: Access Denied: BigQuery BigQuery: Permission denied while writing data.
```

**Comment by emk** [comment]
We have now tried to "fix" this multiple times, but I'm not convinced we understand the actual issue reported here. In particular, we appear to be able to _read_ the temporary bucket in question with no problems. But writing suffers from transient 403 / accessDenied failures. Also surprising: This affects both BigQuery workers talking to GCS on our behalf, _and_ direct access to GCS APIs.

Do not count on this being the last we hear of this issue. We're still guessing, and trying to collect enough data to figure out the pattern.

**Comment by seamusabshere** [comment]
anecdotally, i believe this can be fixed by giving the dbcrossbar service account "Storage Admin" (or similar higher privileges).
